# scenario_test.yaml -exemplo mínimo
# O ideal é que esse arquivo esteja dentro da pasta do cenário, ao lado das subpastas input e output
id: economico
description: "Calculando a dimensão econômica"
base_dir: "."

# aqui fica o DataFrame geral, que congrega todos os dados usados
intermediario: "/home/luca_profissional/Desktop/BolsaLabgest/ish_lunc/dados_gerais/arquivo_intermediario.csv"

dimensions:
  - name: ire_cs_irri_eco
    path: "/home/luca_profissional/Desktop/BolsaLabgest/ish_lunc/functions_module_ish_eco/PAM - ES - Producao irrigada .csv"
    indicadores:
      - name: irri_arroz
        depends_on: []
        pesos: [1,1,1,1,1,1,1] # número de pesos bem acima de qualquer necessidade
      - name: irri_cafe
        depends_on: []
        pesos: [1,1,1,1,1,1,1] # número de pesos bem acima de qualquer necessidade
      - name: irri_cana
        depends_on: []
        pesos: [1,1,1,1,1,1,1] # número de pesos bem acima de qualquer necessidade
      - name: irri_oc
        depends_on: []
        pesos: [1,1,1,1,1,1,1] # número de pesos bem acima de qualquer necessidade
      - name: irri_total
        depends_on: []
        pesos: [1,1,1,1,1,1,1] # número de pesos bem acima de qualquer necessidade
      - name: irri_arroz_risco_iminente
        depends_on: []
        pesos: [1,1,1,1,1,1,1] # número de pesos bem acima de qualquer necessidade
      - name: irri_arroz_risco_pos_deficit
        depends_on: []
        pesos: [1,1,1,1,1,1,1] # número de pesos bem acima de qualquer necessidade
      - name: irri_arroz_risco_total
        depends_on: []
        pesos: [1,1,1,1,1,1,1] # número de pesos bem acima de qualquer necessidade
      - name: irri_cafe_risco_iminente
        depends_on: []
        pesos: [1,1,1,1,1,1,1] # número de pesos bem acima de qualquer necessidade
      - name: irri_cafe_risco_pos_deficit
        depends_on: []
        pesos: [1,1,1,1,1,1,1] # número de pesos bem acima de qualquer necessidade
      - name: irri_cafe_risco_total
        depends_on: []
        pesos: [1,1,1,1,1,1,1] # número de pesos bem acima de qualquer necessidade
      - name: irri_cana_risco_iminente
        depends_on: []
        pesos: [1,1,1,1,1,1,1] # número de pesos bem acima de qualquer necessidade
      - name: irri_cana_risco_pos_deficit
        depends_on: []
        pesos: [1,1,1,1,1,1,1] # número de pesos bem acima de qualquer necessidade
      - name: irri_cana_risco_total
        depends_on: []
        pesos: [1,1,1,1,1,1,1] # número de pesos bem acima de qualquer necessidade
      - name: irri_oc_risco_iminente
        depends_on: []
        pesos: [1,1,1,1,1,1,1] # número de pesos bem acima de qualquer necessidade
      - name: irri_oc_risco_pos_deficit
        depends_on: []
        pesos: [1,1,1,1,1,1,1] # número de pesos bem acima de qualquer necessidade
      - name: irri_oc_risco_total
        depends_on: []
        pesos: [1,1,1,1,1,1,1] # número de pesos bem acima de qualquer necessidade
      - name: irri_total_risco_iminente
        depends_on: []
        pesos: [1,1,1,1,1,1,1] # número de pesos bem acima de qualquer necessidade
      - name: irri_total_risco_pos_deficit
        depends_on: []
        pesos: [1,1,1,1,1,1,1] # número de pesos bem acima de qualquer necessidade
      - name: irri_total_risco_total
        depends_on: []
        pesos: [1,1,1,1,1,1,1] # número de pesos bem acima de qualquer necessidade
      - name: cs_ish_irri
        depends_on: []
        pesos: [1,1,1,1,1,1,1] # número de pesos bem acima de qualquer necessidade
      - name: deman_irri
        depends_on: []
        pesos: [1,1,1,1,1,1,1] # número de pesos bem acima de qualquer necessidade
      - name: densidade_irri
        depends_on: []
        pesos: [1,1,1,1,1,1,1] # número de pesos bem acima de qualquer necessidade
      - name: deman_agri_scbc
        depends_on: []
        pesos: [1,1,1,1,1,1,1] # número de pesos bem acima de qualquer necessidade
      - name: deman_agri_otto
        depends_on: []
        pesos: [1,1,1,1,1,1,1] # número de pesos bem acima de qualquer necessidade
      - name: perc_scbc_irri
        depends_on: []
        pesos: [1,1,1,1,1,1,1] # número de pesos bem acima de qualquer necessidade
      - name: irri_risco_scbc
        depends_on: []
        pesos: [1,1,1,1,1,1,1] # número de pesos bem acima de qualquer necessidade
      - name: cs_ish_scbc_irri
        depends_on: []
        pesos: [1,1,1,1,1,1,1] # número de pesos bem acima de qualquer necessidade
      # - name: irri_scbc
      - name: ire_cs_irri_eco
        depends_on: []
        pesos: [1,1,1,1,1,1,1] # número de pesos bem acima de qualquer necessidade

  - name: ire_cs_pec_eco
    path: "/home/luca_profissional/Desktop/BolsaLabgest/ish_lunc/functions_module_ish_eco/PPM - ES - PPM.csv"
    indicadores:
      - name: pec_bov
      - name: pec_bub
      - name: pec_sui
      - name: pec_cap
      - name: pec_ovi
      - name: pec_gal
      - name: pec_total
      - name: pec_risco_iminente
      - name: pec_risco_pos_deficit
      - name: pec_risco_total
      - name: cs_ish_pec
      - name: deman_pecuaria
      - name: densidade_pec
      - name: deman_pecuaria_scbc
      - name: deman_pecuaria_otto
      - name: perc_deman_pecuaria
      - name: ihu_cs_ish_pec
      - name: ire_cs_pec_eco

  - name: ire_cs_ind_eco
    path: "/home/luca_profissional/Desktop/BolsaLabgest/ish_lunc/functions_module_ish_eco/Indicador Industria - Bernardo - Ind_sc_otto.csv"
    indicadores:
      - name: ihu_nu_indriscoinerente
      - name: ihu_nu_indriscoposdeficit
      - name: ihu_nu_indriscototal
      - name: ihu_cs_ish_ind
      - name: deman_indus
      - name: densidade_ind
      - name: dem_ind_scbc
      - name: dem_ind_bacia
      - name: perc_scbc_ind
      - name: ihu_rel_ind
      - name: ire_cs_ind_eco

result:
  - name: ire_cs_eco
    depends_on:
      - name: ire_cs_ind_eco
        peso: 1
      - name: ire_cs_irri_eco
        peso: 0.7
      - name: ire_cs_pec_eco
        peso: 0.3

# Saída: pode opcionalmente sobrescrever pasta output/gpkg final
output:
  path: "/home/luca_profissional/Desktop/BolsaLabgest/ish_lunc/functions_module_ish_eco/output/ish_eco.csv"