# scenario_test.yaml -exemplo mínimo
# O ideal é que esse arquivo esteja dentro da pasta do cenário, ao lado das subpastas input e output
id: economico
description: "Calculando a dimensão econômica"
base_dir: "."

bho:
  path: "/home/luca_profissional/Desktop/BolsaLabgest/ish_lunc/cnr_A/input/BHO_area.gpkg"

dimensions:
  - name: ire_cs_ind_eco
    path: "./Indicador Industria - Bernardo - Ind_sc_otto.csv"
    indicadores:
      - name: disp_por_dem
        depends_on:
          - name: bal_perc
      - name: fator_iminente
        depends_on: 
          - name: disp_por_dem
      - name: fator_pos_deficit
        depends_on: 
          - name: disp_por_dem
      - name: fator_de_risco_total
        depends_on: 
          - name: fator_iminente
          - name: fator_pos_deficit
      - name: ihu_nu_popriscoinerente
        depends_on: 
          - name: fator_iminente
          - name: dmu_nu_popurbana
      - name: ihu_pc_risco_inerente
        depends_on: 
          - name: ihu_nu_popriscoinerente
          - name: dmu_nu_popurbana
      - name: ihu_nu_popriscoposdeficit
        depends_on: 
          - name: fator_pos_deficit
          - name: dmu_nu_popurbana
      - name: ihu_pc_riscoposdeficit
        depends_on: 
          - name: ihu_nu_popriscoposdeficit
          - name: dmu_nu_popurbana
      - name: ihu_nu_popriscototal
        depends_on: 
          - name: fator_de_risco_total
          - name: dmu_nu_popurbana
      - name: ihu_cs_ish
        depends_on:
          - name: ihu_nu_popriscototal
          - name: fator_de_risco_total
      - name: deman_indus
        depends_on:
          - name: COBACIA
      - name: densidade
        depends_on:
          - name: deman_indus
          - name: area_otto
      - name: pop_urb_scbc
        depends_on:
          - name: situacao_setor
          - name: densidade
          - name: area_scbc
      - name: pop_urb_bacia
        depends_on:
          - name: COBACIA
          - name: pop_urb_scbc
      - name: perc_scbc
        depends_on:
          - name: pop_urb_scbc
          - name: deman_indus
      - name: ihu_rel
        depends_on:
          - name: perc_scbc
          - name: ihu_cs_ish
      - name: ire_cs_ind_eco
        depends_on:
          - name: COBACIA
          - name: ihu_rel
    
  - name: ire_cs_irri_eco
    path: "./PAM - ES - Agr_otto.csv"
    indicadores:
      - name: ire_cs_irri_eco
  - name: ire_cs_pec_eco
    path: "./PPM - ES - Pec_otto.csv"
    indicadores:
      - name: ire_cs_pec_eco

result:
  - name: ire_cs_eco
    depends_on:
      - name: ire_cs_ind_eco
        peso: 1
      - name: ire_cs_irri_eco
        peso: 0.7
      - name: ire_cs_pec_eco
        peso: 0.3

# Saída: pode opcionalmente sobrescrever pasta output/gpkg final
output:
  path: "./output/ish_eco.csv"

# logging / metadados (opcional)
metadata:
  manifest: "./output/my_new_dimensions_cenario_manifest.json"
 