id: humano
description: "Calculando a dimensão humana"
base_dir: "."

bho:
  path: "/home/luca_profissional/Desktop/BolsaLabgest/ish_lunc/cnr_A/input/BHO_area.gpkg"

dimensions:
  - name: ire_cs_hum
    path: "./dimensao_humana.csv"
    indicadores:
      - name: disp_por_dem
        depends_on: 
          - name: bal_perc
      - name: fator_iminente
        depends_on: 
          - name: disp_por_dem
      - name: fator_pos_deficit
        depends_on: 
          - name: disp_por_dem
      - name: fator_de_risco_total
        depends_on: 
          - name: fator_iminente
          - name: fator_pos_deficit
      - name: ihu_nu_popriscoinerente
        depends_on: 
          - name: fator_iminente
          - name: dmu_nu_popurbana
      - name: ihu_pc_risco_inerente
        depends_on: 
          - name: ihu_nu_popriscoinerente
          - name: dmu_nu_popurbana
      - name: ihu_nu_popriscoposdeficit
        depends_on: 
          - name: fator_pos_deficit
          - name: dmu_nu_popurbana
      - name: ihu_pc_riscoposdeficit
        depends_on: 
          - name: ihu_nu_popriscoposdeficit
          - name: dmu_nu_popurbana
      - name: ihu_nu_popriscototal
        depends_on: 
          - name: fator_de_risco_total
          - name: dmu_nu_popurbana
      - name: ihu_pc_risco
        depends_on: 
          - name: ihu_nu_popriscototal
          - name: dmu_nu_popurbana
      - name: densidade
        depends_on: 
          - name: pop
          - name: area_setor
      - name: cs_risco
        depends_on: 
          - name: ihu_nu_popriscototal
          - name: ihu_pc_risco
      - name: cs_cobred
        depends_on: 
          - name: ihu_pc_cobrede
      - name: perc_scbc
        depends_on: 
          - name: pop_urb_scbc
          - name: pop_urb_bacia
      - name: ihu_cs_ish
        depends_on:
          - name: cs_risco
            peso: 0.7
          - name: cs_cobred
            peso: 0.3
      - name: ihu_rel_pop
        depends_on: 
          - name: perc_scbc
          - name: cs_risco
      - name: ihu_rel_cobred
        depends_on: 
          - name: perc_scbc
          - name: cs_cobred
      - name: ire_hu_pop
        depends_on: 
          - name: ihu_rel_pop
          - name: COBACIA
      - name: ire_hu_cobred
        depends_on: 
         - name: ihu_rel_cobred
         - name: COBACIA
    descritor: tipo_setor

result:
  - name: ire_cs_hum
    depends_on:
      - name: ire_hu_cobred
        peso: 0.7
      - name: ire_hu_pop
        peso: 0.3

# Saída: pode opcionalmente sobrescrever pasta output/gpkg final
output:
  path: "./output/ish_hum.csv"

# logging / metadados (opcional)
metadata:
  manifest: "./output/my_new_dimensions_cenario_manifest.json"
 
