# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HelloWorld
                                 A QGIS plugin
 Editor de Regras em Massa para campos
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-07
        copyright            : (C) 2026 by Luca Avila
        email                : lucaavila.profissional@gmail.com
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QCoreApplication, Qt
from qgis.core import (
    QgsProject, QgsVectorLayer, QgsFeature, 
    QgsExpression, QgsFeatureRequest
)
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import (
    QAction, QMessageBox, QDialog, QVBoxLayout, QHBoxLayout,
    QComboBox, QLineEdit, QPushButton, QLabel, QGroupBox,
    QCheckBox, QTextEdit, QTabWidget, QWidget
)
from qgis.PyQt.QtCore import QVariant
import os.path


class HelloWorld:
    """QGIS Plugin Implementation - Editor de Regras em Massa"""

    def __init__(self, iface):
        """Constructor."""
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        self.actions = []
        self.menu = self.tr(u'&Editor de Regras')
        self.first_start = None

    def tr(self, message):
        return QCoreApplication.translate('HelloWorld', message)

    def add_action(self, icon_path, text, callback, parent=None):
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        self.iface.addPluginToMenu(self.menu, action)
        self.iface.addToolBarIcon(action)
        self.actions.append(action)
        return action

    def initGui(self):
        """Create the menu entries and toolbar icons."""
        icon_path = os.path.join(os.path.dirname(__file__), 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr(u'📊 Editor de Regras em Massa'),
            callback=self.run,
            parent=self.iface.mainWindow()
        )
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon."""
        for action in self.actions:
            self.iface.removePluginMenu(self.tr(u'&Editor de Regras'), action)
            self.iface.removeToolBarIcon(action)

    # ============================================================
    # FUNÇÃO PRINCIPAL - ABRE O EDITOR
    # ============================================================
    
    def run(self):
        """Executa o plugin - abre o editor de regras"""
        layer = self.iface.activeLayer()
        
        if not layer or not isinstance(layer, QgsVectorLayer):
            QMessageBox.warning(self.iface.mainWindow(), "Aviso", 
                "Selecione uma camada vetorial na legenda.")
            return
        
        # Cria o diálogo
        dialog = QDialog(self.iface.mainWindow())
        dialog.setWindowTitle("📊 Editor de Regras em Massa")
        dialog.setMinimumWidth(700)
        dialog.setMinimumHeight(500)
        dialog.setModal(True)
        
        layout_principal = QVBoxLayout()
        
        # === INFORMAÇÕES DA CAMADA ===
        info_layer = QLabel(f"📌 Camada: {layer.name()} | Feições: {layer.featureCount()} | "
                           f"Selecionadas: {layer.selectedFeatureCount()}")
        info_layer.setStyleSheet("font-weight: bold; padding: 5px; background-color: #e3f2fd; border-radius: 3px;")
        layout_principal.addWidget(info_layer)
        
        # === ABAS ===
        tabs = QTabWidget()
        
        # --- ABA 1: REGRA SIMPLES ---
        tab_simples = QWidget()
        layout_simples = QVBoxLayout()
        
        grupo_origem = QGroupBox("1️⃣ Campo de Origem (referência)")
        grupo_origem_layout = QVBoxLayout()
        
        lbl_campo_origem = QLabel("Selecione o campo que será usado como referência:")
        combo_origem = QComboBox()
        for field in layer.fields():
            combo_origem.addItem(f"{field.name()} ({field.typeName()})", field.name())
        
        # Seleciona 'bal_perc' se existir
        bal_index = combo_origem.findData('bal_perc')
        if bal_index >= 0:
            combo_origem.setCurrentIndex(bal_index)
        
        grupo_origem_layout.addWidget(lbl_campo_origem)
        grupo_origem_layout.addWidget(combo_origem)
        grupo_origem.setLayout(grupo_origem_layout)
        layout_simples.addWidget(grupo_origem)
        
        grupo_regra = QGroupBox("2️⃣ Defina a Regra")
        grupo_regra_layout = QVBoxLayout()
        
        lbl_regra = QLabel("Fórmula para calcular o novo valor:")
        input_formula = QLineEdit()
        input_formula.setPlaceholderText("Ex: valor * 2 + 10  (use 'valor' para o valor do campo de origem)")
        input_formula.setText("valor + 60")
        
        lbl_exemplos = QLabel("💡 Exemplos: valor * 1.5 | valor + 100 | valor / 2 | valor - 10")
        lbl_exemplos.setStyleSheet("font-size: 9pt; color: #666;")
        
        grupo_regra_layout.addWidget(lbl_regra)
        grupo_regra_layout.addWidget(input_formula)
        grupo_regra_layout.addWidget(lbl_exemplos)
        grupo_regra.setLayout(grupo_regra_layout)
        layout_simples.addWidget(grupo_regra)
        
        grupo_destino = QGroupBox("3️⃣ Campo de Destino")
        grupo_destino_layout = QVBoxLayout()
        
        lbl_campo_destino = QLabel("Campo que receberá o novo valor:")
        combo_destino = QComboBox()
        for field in layer.fields():
            combo_destino.addItem(f"{field.name()} ({field.typeName()})", field.name())
        
        # Seleciona 'pop' se existir
        pop_index = combo_destino.findData('pop')
        if pop_index >= 0:
            combo_destino.setCurrentIndex(pop_index)
        
        grupo_destino_layout.addWidget(lbl_campo_destino)
        grupo_destino_layout.addWidget(combo_destino)
        grupo_destino.setLayout(grupo_destino_layout)
        layout_simples.addWidget(grupo_destino)
        
        tab_simples.setLayout(layout_simples)
        tabs.addTab(tab_simples, "📝 Regra Simples")
        
        # --- ABA 2: REGRA AVANÇADA (com condições) ---
        tab_avancado = QWidget()
        layout_avancado = QVBoxLayout()
        
        grupo_condicao = QGroupBox("🎯 Condição (opcional)")
        grupo_condicao_layout = QVBoxLayout()
        
        lbl_condicao = QLabel("Aplicar apenas quando a condição for verdadeira:")
        input_condicao = QLineEdit()
        input_condicao.setPlaceholderText("Ex: \"pop\" > 100 AND \"categoria\" = 'A'")
        
        lbl_cond_extra = QLabel("💡 Use nomes de campos entre aspas duplas: \"campo\"")
        lbl_cond_extra.setStyleSheet("font-size: 9pt; color: #666;")
        
        grupo_condicao_layout.addWidget(lbl_condicao)
        grupo_condicao_layout.addWidget(input_condicao)
        grupo_condicao_layout.addWidget(lbl_cond_extra)
        grupo_condicao.setLayout(grupo_condicao_layout)
        layout_avancado.addWidget(grupo_condicao)
        
        # Filtro por seleção
        check_selecionados = QCheckBox("✅ Aplicar apenas nas feições selecionadas")
        if layer.selectedFeatureCount() > 0:
            check_selecionados.setText(f"✅ Apenas feições selecionadas ({layer.selectedFeatureCount()} feições)")
            check_selecionados.setChecked(True)
        else:
            check_selecionados.setText("✅ Apenas feições selecionadas (nenhuma selecionada)")
            check_selecionados.setEnabled(False)
        
        layout_avancado.addWidget(check_selecionados)
        
        tab_avancado.setLayout(layout_avancado)
        tabs.addTab(tab_avancado, "⚙️ Avançado")
        
        layout_principal.addWidget(tabs)
        
        # --- ÁREA DE PRÉ-VISUALIZAÇÃO ---
        grupo_preview = QGroupBox("👁️ Pré-visualização")
        grupo_preview_layout = QVBoxLayout()
        
        text_preview = QTextEdit()
        text_preview.setReadOnly(True)
        text_preview.setMaximumHeight(150)
        text_preview.setStyleSheet("font-family: monospace; font-size: 10pt;")
        
        btn_preview = QPushButton("🔍 Atualizar Pré-visualização")
        btn_preview.setStyleSheet("background-color: #FF9800; color: white; font-weight: bold; padding: 5px;")
        
        grupo_preview_layout.addWidget(text_preview)
        grupo_preview_layout.addWidget(btn_preview)
        grupo_preview.setLayout(grupo_preview_layout)
        layout_principal.addWidget(grupo_preview)
        
        # --- BOTÕES DE AÇÃO ---
        layout_botoes = QHBoxLayout()
        
        btn_aplicar = QPushButton("✅ Aplicar Regra")
        btn_aplicar.setStyleSheet("""
            QPushButton {
                background-color: #4CAF50; 
                color: white; 
                font-weight: bold; 
                padding: 12px;
                border-radius: 5px;
                font-size: 12pt;
            }
            QPushButton:hover { background-color: #45a049; }
        """)
        
        btn_fechar = QPushButton("❌ Fechar")
        btn_fechar.setStyleSheet("""
            QPushButton {
                background-color: #f44336; 
                color: white; 
                font-weight: bold; 
                padding: 12px;
                border-radius: 5px;
            }
            QPushButton:hover { background-color: #D32F2F; }
        """)
        
        layout_botoes.addWidget(btn_aplicar)
        layout_botoes.addWidget(btn_fechar)
        layout_principal.addLayout(layout_botoes)
        
        dialog.setLayout(layout_principal)
        
        # ============================================================
        # FUNÇÕES DO DIÁLOGO
        # ============================================================
        
        def get_features_to_edit():
            """Retorna as feições que serão editadas"""
            features = []
            
            # Verifica se usa apenas selecionados
            if check_selecionados.isEnabled() and check_selecionados.isChecked():
                features = list(layer.selectedFeatures())
            else:
                # Verifica condição avançada
                condicao = input_condicao.text().strip()
                if condicao:
                    try:
                        expr = QgsExpression(condicao)
                        request = QgsFeatureRequest(expr)
                        features = list(layer.getFeatures(request))
                    except:
                        features = list(layer.getFeatures())
                else:
                    features = list(layer.getFeatures())
            
            return features
        
        def calcular_novo_valor(valor_origem, formula):
            """Calcula o novo valor baseado na fórmula"""
            try:
                # Substitui 'valor' pelo valor real
                formula_segura = formula.replace('valor', str(valor_origem))
                # Avalia a expressão
                resultado = eval(formula_segura)
                return resultado
            except:
                return None
        
        def preview_alteracoes():
            """Mostra pré-visualização das alterações"""
            campo_origem = combo_origem.currentData()
            campo_destino = combo_destino.currentData()
            formula = input_formula.text().strip()
            
            if not formula:
                text_preview.setText("⚠️ Digite uma fórmula primeiro.")
                return
            
            features = get_features_to_edit()
            
            if not features:
                text_preview.setText("⚠️ Nenhuma feição encontrada com os critérios atuais.")
                return
            
            # Constrói o preview
            texto = f"📋 Regra: {campo_destino} = {formula} (onde 'valor' = {campo_origem})\n"
            texto += f"📌 Feições afetadas: {len(features)}\n"
            texto += "━" * 50 + "\n\n"
            
            # Mostra as primeiras 10
            count = 0
            for feat in features[:10]:
                valor_origem = feat.attribute(campo_origem)
                novo_valor = calcular_novo_valor(valor_origem, formula)
                
                if novo_valor is not None:
                    valor_atual = feat.attribute(campo_destino)
                    texto += f"Feição {feat.id()}: {campo_origem}={valor_origem} → "
                    texto += f"{campo_destino}: {valor_atual} → {novo_valor}\n"
                    count += 1
                else:
                    texto += f"Feição {feat.id()}: ⚠️ Erro ao calcular (valor_origem={valor_origem})\n"
            
            if len(features) > 10:
                texto += f"\n... e mais {len(features) - 10} feições"
            
            if count == 0:
                texto += "\n⚠️ Nenhuma feição pôde ser calculada. Verifique a fórmula."
            
            text_preview.setText(texto)
        
        def aplicar_regra():
            """Aplica a regra nas feições"""
            campo_origem = combo_origem.currentData()
            campo_destino = combo_destino.currentData()
            formula = input_formula.text().strip()
            
            if not formula:
                QMessageBox.warning(dialog, "Aviso", "Digite uma fórmula.")
                return
            
            features = get_features_to_edit()
            
            if not features:
                QMessageBox.warning(dialog, "Aviso", "Nenhuma feição encontrada para editar.")
                return
            
            # Conta quantas serão realmente alteradas
            validas = 0
            for feat in features:
                valor_origem = feat.attribute(campo_origem)
                novo_valor = calcular_novo_valor(valor_origem, formula)
                if novo_valor is not None:
                    validas += 1
            
            if validas == 0:
                QMessageBox.warning(dialog, "Aviso", 
                    "Nenhuma feição pôde ser calculada. Verifique a fórmula e os valores.")
                return
            
            # Confirmação
            resposta = QMessageBox.question(
                dialog,
                "Confirmar",
                f"Tem certeza que deseja aplicar a regra?\n\n"
                f"📌 Feições afetadas: {validas}\n"
                f"📝 Regra: {campo_destino} = {formula}\n"
                f"📌 Campo de origem: {campo_origem}\n\n"
                f"⚠️ Esta ação não pode ser desfeita!",
                QMessageBox.Yes | QMessageBox.No
            )
            
            if resposta != QMessageBox.Yes:
                return
            
            # Aplica
            try:
                if not layer.isEditable():
                    layer.startEditing()
                
                count = 0
                erros = []
                
                for feat in features:
                    valor_origem = feat.attribute(campo_origem)
                    novo_valor = calcular_novo_valor(valor_origem, formula)
                    
                    if novo_valor is not None:
                        # Verifica o tipo do campo destino
                        field = layer.fields().field(campo_destino)
                        tipo = field.type()
                        
                        # Converte para o tipo correto
                        if tipo in (QVariant.Int, QVariant.LongLong):
                            novo_valor = int(novo_valor)
                        elif tipo in (QVariant.Double, QVariant.UserType):
                            novo_valor = float(novo_valor)
                        
                        feat.setAttribute(campo_destino, novo_valor)
                        layer.updateFeature(feat)
                        count += 1
                    else:
                        erros.append(feat.id())
                
                # Salva
                if layer.commitChanges():
                    QMessageBox.information(dialog, "✅ Sucesso", 
                        f"{count} feição(ões) atualizadas com sucesso!\n\n"
                        f"📝 Regra: {campo_destino} = {formula}\n"
                        f"📌 Campo de origem: {campo_origem}\n"
                        f"📌 Campo de destino: {campo_destino}\n"
                        f"⚠️ Feições com erro: {len(erros)}"
                    )
                    dialog.accept()
                    self.iface.mapCanvas().refresh()
                else:
                    erros_commit = layer.commitErrors()
                    QMessageBox.critical(dialog, "❌ Erro", 
                        f"Erro ao salvar:\n{erros_commit}")
                    layer.rollBack()
                    
            except Exception as e:
                QMessageBox.critical(dialog, "❌ Erro", f"Erro ao aplicar: {str(e)}")
                if layer.isEditable():
                    layer.rollBack()
        
        # Conecta os botões
        btn_preview.clicked.connect(preview_alteracoes)
        btn_aplicar.clicked.connect(aplicar_regra)
        btn_fechar.clicked.connect(dialog.reject)
        
        # Pré-visualização automática
        input_formula.textChanged.connect(preview_alteracoes)
        combo_origem.currentIndexChanged.connect(preview_alteracoes)
        combo_destino.currentIndexChanged.connect(preview_alteracoes)
        
        # Preview inicial
        preview_alteracoes()
        
        dialog.exec_()