# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HelloWorld
                                 A QGIS plugin
 Imprime Hello World
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-06-23
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Luca Avila
        email                : lucaavila.profissional@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QLocale, QTranslator, QCoreApplication
from qgis.core import QgsSettings
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.PyQt.QtWidgets import QMessageBox, QInputDialog

# Import the code for the dialog
from .hello_world_dialog import HelloWorldDialog
import os.path


class HelloWorld:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QgsSettings().value('locale/userLocale', QLocale().name())[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            '{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Hello World')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('HelloWorld', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = os.path.join(os.path.dirname(__file__), 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr(u'Botão para Hello World'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Hello World'),
                action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        """Código que executa quando o usuário clica no botão do plugin."""
        
        # 1. Pega a camada ativa que está selecionada na legenda do QGIS
        layer = self.iface.activeLayer()
        
        # Validação: Verifica se existe uma camada selecionada
        if not layer:
            from qgis.PyQt.QtWidgets import QMessageBox
            QMessageBox.warning(self.iface.mainWindow(), "Aviso", "Por favor, selecione uma camada na legenda primeiro.")
            return
        
        # 2. Pega os campos da camada para exibir na caixa de diálogo
        fields = layer.fields()
        field_names = [field.name() for field in fields]
        
        if not field_names:
            from qgis.PyQt.QtWidgets import QMessageBox
            QMessageBox.warning(self.iface.mainWindow(), "Aviso", "A camada selecionada não possui campos para editar.")
            return
        
        # 3. Importações necessárias concentradas
        from qgis.PyQt.QtWidgets import QDialog, QVBoxLayout, QComboBox, QLineEdit, QPushButton, QLabel, QHBoxLayout, QGroupBox, QMessageBox
        from qgis.PyQt.QtCore import Qt, QVariant
        from qgis.gui import QgsMapToolEmitPoint, QgsRubberBand
        from qgis.core import QgsGeometry, QgsPointXY, QgsWkbTypes, QgsCoordinateTransform, QgsProject, QgsFeatureRequest
        from PyQt5.QtGui import QColor
        import traceback
        
        # Criamos o diálogo referenciando a janela principal
        dialog = QDialog(self.iface.mainWindow())
        dialog.setWindowTitle("Editar Dados por Seleção no Mapa")
        dialog.setMinimumWidth(450)
        dialog.setMinimumHeight(400)
        
        # GARANTE QUE NÃO BLOQUEIE O MAPA (A janela fica por cima, mas permite clicar ao fundo)
        dialog.setWindowModality(Qt.NonModal)
        
        layout = QVBoxLayout()
        
        # Instruções
        lbl_instrucao = QLabel("Clique no botão abaixo e depois clique em um elemento no mapa para selecioná-lo")
        lbl_instrucao.setStyleSheet("font-weight: bold; color: #2196F3;")
        layout.addWidget(lbl_instrucao)
        
        # Botão para ativar o modo de seleção
        btn_selecionar = QPushButton("🔍 Selecionar elemento no mapa")
        btn_selecionar.setStyleSheet("""
            QPushButton {
                background-color: #4CAF50; 
                color: white; 
                font-weight: bold; 
                padding: 10px;
                border-radius: 5px;
            }
            QPushButton:hover {
                background-color: #45a049;
            }
        """)
        layout.addWidget(btn_selecionar)
        
        # Grupo para mostrar a feição selecionada
        group_selecao = QGroupBox("Elemento Selecionado")
        group_selecao.setStyleSheet("QGroupBox { font-weight: bold; }")
        group_layout = QVBoxLayout()
        
        lbl_feicao = QLabel("Nenhuma feição selecionada")
        lbl_feicao.setStyleSheet("""
            border: 2px solid #ccc; 
            padding: 8px; 
            background-color: #f9f9f9;
            border-radius: 3px;
            font-family: monospace;
            min-height: 60px;
        """)
        lbl_feicao.setWordWrap(True)
        group_layout.addWidget(lbl_feicao)
        group_selecao.setLayout(group_layout)
        layout.addWidget(group_selecao)
        
        # Seleção do campo
        layout.addWidget(QLabel("📝 Selecione o campo para editar:"))
        combo_campos = QComboBox()
        combo_campos.addItems(field_names)
        combo_campos.setStyleSheet("padding: 5px;")
        layout.addWidget(combo_campos)
        
        # Novo valor
        layout.addWidget(QLabel("✏️ Digite o novo valor:"))
        input_valor = QLineEdit()
        input_valor.setPlaceholderText("Digite o novo valor aqui...")
        input_valor.setStyleSheet("padding: 5px;")
        layout.addWidget(input_valor)
        
        # Botões OK/Cancelar
        btn_layout = QHBoxLayout()
        btn_ok = QPushButton("✅ Aplicar Alterações")
        btn_ok.setStyleSheet("""
            QPushButton {
                background-color: #2196F3; 
                color: white; 
                font-weight: bold; 
                padding: 10px;
                border-radius: 5px;
            }
            QPushButton:hover {
                background-color: #1976D2;
            }
        """)
        btn_cancelar = QPushButton("❌ Cancelar")
        btn_cancelar.setStyleSheet("""
            QPushButton {
                background-color: #f44336; 
                color: white; 
                font-weight: bold; 
                padding: 10px;
                border-radius: 5px;
            }
            QPushButton:hover {
                background-color: #D32F2F;
            }
        """)
        
        btn_layout.addWidget(btn_ok)
        btn_layout.addWidget(btn_cancelar)
        layout.addLayout(btn_layout)
        
        dialog.setLayout(layout)
        
        # Variáveis de controle persistentes no escopo do método
        selected_feature_id = None
        selection_rubberband = None
        map_tool = None
        
        # Função interna para atualizar a interface com os dados da feição
        def carregar_dados_feicao(feat):
            nonlocal selected_feature_id, selection_rubberband
            
            # Armazena o ID interno correto do QGIS para a edição apontar para a feição certa
            selected_feature_id = feat.id()
            
            # Remove rubberband anterior se existir
            if selection_rubberband:
                selection_rubberband.reset()
                selection_rubberband = None
            
            # Cria um rubberband para destacar a feição geometricamente
            is_polygon = feat.geometry().type() == QgsWkbTypes.PolygonGeometry
            selection_rubberband = QgsRubberBand(self.iface.mapCanvas(), QgsWkbTypes.PolygonGeometry if is_polygon else QgsWkbTypes.LineGeometry)
            selection_rubberband.setColor(QColor(255, 0, 0, 100))
            selection_rubberband.setWidth(3)
            selection_rubberband.setToGeometry(feat.geometry(), layer)
            
            # Mostra informações da feição selecionada
            info_text = f"✅ Feição ID Interno QGIS: {selected_feature_id}\n"
            info_text += "━" * 30 + "\n"
            for field in field_names:
                value = feat[field]
                if value is None:
                    value = "NULL"
                info_text += f"{field}: {value}\n"
            
            lbl_feicao.setText(info_text)
            lbl_feicao.setStyleSheet("""
                border: 2px solid #4CAF50; 
                padding: 8px; 
                background-color: #e8f5e9;
                border-radius: 3px;
                font-family: monospace;
                min-height: 60px;
            """)

        # Se o usuário já tiver selecionado elementos no mapa antes de abrir o plugin, carrega o primeiro
        if layer.selectedFeatureCount() > 0:
            carregar_dados_feicao(layer.selectedFeatures()[0])
        
        # Função para selecionar elemento pelo clique no mapa
        def select_feature_by_click(point):
            try:
                # Limpa a seleção visual anterior
                layer.removeSelection()
                
                # Transforma o ponto clicado (CRS do mapa) para o CRS da camada caso sejam diferentes
                canvas_crs = self.iface.mapCanvas().mapSettings().destinationCrs()
                layer_crs = layer.crs()
                
                ponto_camada = point
                if canvas_crs != layer_crs:
                    xform = QgsCoordinateTransform(canvas_crs, layer_crs, QgsProject.instance())
                    ponto_camada = xform.transform(point)
                
                geom_ponto_clique = QgsGeometry.fromPointXY(ponto_camada)
                
                # Cria uma pequena caixa de busca (Bounding Box) dinâmica baseada na escala do mapa
                escala = self.iface.mapCanvas().scale()
                tolerancia = escala * 0.002  # Ajuste de sensibilidade
                busca_rect = QgsGeometry.fromPointXY(ponto_camada).buffer(tolerancia, 5).boundingBox()
                
                # Filtra espacialmente apenas as feições que estão cruzando a área do clique
                request = QgsFeatureRequest().setFilterRect(busca_rect)
                
                closest_feature = None
                menor_distancia = float('inf')
                
                for feature in layer.getFeatures(request):
                    if not feature.geometry():
                        continue
                    
                    # Prioridade absoluta: o clique ocorreu DENTRO do polígono
                    if feature.geometry().contains(geom_ponto_clique):
                        closest_feature = feature
                        break
                    
                    # Fallback (para linhas/pontos ou cliques na borda): calcula a feição mais próxima
                    dist = feature.geometry().distance(geom_ponto_clique)
                    if dist < menor_distancia:
                        menor_distancia = dist
                        closest_feature = feature
                
                if closest_feature:
                    layer.selectByIds([closest_feature.id()])
                    carregar_dados_feicao(closest_feature)
                    
                    # Restaura a ferramenta original após o clique com sucesso
                    self.iface.mapCanvas().setMapTool(None)
                    restore_button_style()
                else:
                    QMessageBox.warning(dialog, "Aviso", "Nenhum elemento encontrado próximo ao clique. Tente aproximar o zoom.")
                    
            except Exception as e:
                erro_detalhado = traceback.format_exc()
                QMessageBox.critical(dialog, "Erro ao processar clique", f"Ocorreu uma falha interna:\n\n{erro_detalhado}")
        
        # Função para ativar o modo de seleção
        def activate_selection_mode():
            nonlocal map_tool
            
            # Cria e ativa a ferramenta de clique
            map_tool = QgsMapToolEmitPoint(self.iface.mapCanvas())
            map_tool.canvasClicked.connect(select_feature_by_click)
            self.iface.mapCanvas().setMapTool(map_tool)
            
            # Feedback visual do botão ativo
            btn_selecionar.setStyleSheet("""
                QPushButton {
                    background-color: #FF9800; 
                    color: white; 
                    font-weight: bold; 
                    padding: 10px;
                    border-radius: 5px;
                }
            """)
            btn_selecionar.setText("🔄 Clique em um elemento no mapa...")
        
        def restore_button_style():
            btn_selecionar.setStyleSheet("""
                QPushButton {
                    background-color: #4CAF50; 
                    color: white; 
                    font-weight: bold; 
                    padding: 10px;
                    border-radius: 5px;
                }
                QPushButton:hover {
                    background-color: #45a049;
                }
            """)
            btn_selecionar.setText("🔍 Selecionar elemento no mapa")
        
        btn_selecionar.clicked.connect(activate_selection_mode)
        
        # Função para aplicar as alterações na sessão e atualizar a aba "Resultados de Identificar"
        def aplicar_alteracoes():
            nonlocal selection_rubberband
            
            if selected_feature_id is None:
                QMessageBox.warning(dialog, "Aviso", "Por favor, selecione um elemento no mapa primeiro.")
                return
            
            campo_selecionado = combo_campos.currentText()
            texto_novo_valor = input_valor.text().strip()
            
            if not texto_novo_valor:
                QMessageBox.warning(dialog, "Aviso", "Por favor, digite um novo valor.")
                return
            
            # Encontra o índice numérico da coluna
            field_index = layer.fields().indexFromName(campo_selecionado)
            if field_index == -1:
                QMessageBox.critical(dialog, "Erro", f"A coluna '{campo_selecionado}' não foi encontrada.")
                return
            
            # --- CONVERSÃO DE TIPOS ---
            campo_tipo = layer.fields().at(field_index).type()
            from PyQt5.QtCore import QVariant
            try:
                if campo_tipo in (QVariant.Int, QVariant.LongLong):
                    novo_valor = int(texto_novo_valor)
                elif campo_tipo in (QVariant.Double, QVariant.UserType):
                    novo_valor = float(texto_novo_valor.replace(',', '.'))
                else:
                    novo_valor = texto_novo_valor
            except ValueError:
                QMessageBox.warning(dialog, "Erro de Tipo", f"O campo '{campo_selecionado}' espera um valor numérico válido.")
                return
            
            try:
                # 1. Abre edição em rascunho (memória do QGIS)
                if not layer.isEditable():
                    layer.startEditing()
                
                # 2. Modifica o atributo
                sucesso = layer.changeAttributeValue(selected_feature_id, field_index, novo_valor)
                
                if sucesso:
                    # Notifica as ferramentas do QGIS sobre a mudança
                    layer.attributeValueChanged.emit(selected_feature_id, field_index, novo_valor)
                    layer.updateFeature(layer.getFeature(selected_feature_id))
                    
                    # 🔥 ATUALIZAÇÃO SEGURA DA ABA LATERAL (Sem quebrar o import do QGIS)
                    from PyQt5.QtWidgets import QDockWidget
                    # Buscamos todas as abas/painéis laterais genéricos (QDockWidget) da janela do QGIS
                    docks = self.iface.mainWindow().findChildren(QDockWidget)
                    for dock in docks:
                        # Verificamos se é o painel de identificação e se ele está aberto na tela
                        if dock.objectName() == "QgsIdentifyResultsDock" and dock.isVisible():
                            # Se o método nativo refreshResults existir no objeto retornado, nós o chamamos
                            if hasattr(dock, 'refreshResults'):
                                dock.refreshResults()
                            # Caso o método direto varie na sua versão, forçamos o repaint do widget interno
                            elif dock.widget():
                                dock.widget().update()
                    
                    QMessageBox.information(dialog, "Sucesso", 
                        f"✅ Valor alterado na sessão do QGIS!\n"
                        f"⚠️ O arquivo original GeoPackage NÃO foi modificado.\n\n"
                        f"📌 ID Interno: {selected_feature_id}\n"
                        f"📝 Campo: {campo_selecionado}\n"
                        f"🔄 Novo valor: {novo_valor}")
                else:
                    QMessageBox.critical(dialog, "Erro", "O QGIS não conseguiu aplicar a alteração na memória.")
                    return
                
                # Limpa o destaque vermelho do clique
                if selection_rubberband:
                    selection_rubberband.reset()
                    selection_rubberband = None
                
                # 3. Redesenha a tela do mapa
                layer.triggerRepaint()
                self.iface.mapCanvas().refreshAllLayers()
                
                # Fecha a janela do plugin
                dialog.accept()
                
            except Exception as e:
                QMessageBox.critical(dialog, "Erro ao alterar", f"❌ Falha na edição em memória:\n{str(e)}")
                
        # Função para limpar recursos quando a janela for encerrada de qualquer forma
        def ao_encerrar_dialog():
            nonlocal selection_rubberband
            if selection_rubberband:
                selection_rubberband.reset()
                selection_rubberband = None
            if self.iface.mapCanvas().mapTool() == map_tool:
                self.iface.mapCanvas().setMapTool(None)
            layer.removeSelection()
            self.iface.mapCanvas().refresh()

        btn_ok.clicked.connect(aplicar_alteracoes)
        btn_cancelar.clicked.connect(dialog.reject)
        dialog.finished.connect(ao_encerrar_dialog)
        
        # Abre a interface de forma Não-Bloqueante
        dialog.show()