# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HelloWorld
                                 A QGIS plugin
 Editor de Fórmulas com Múltiplas Colunas
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-07
        copyright            : (C) 2026 by Luca Avila
        email                : lucaavila.profissional@gmail.com
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QCoreApplication, Qt
from qgis.core import (
    QgsProject, QgsVectorLayer, QgsFeature, 
    QgsExpression, QgsFeatureRequest, QgsField
)
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import (
    QAction, QMessageBox, QDialog, QVBoxLayout, QHBoxLayout,
    QComboBox, QLineEdit, QPushButton, QLabel, QGroupBox,
    QCheckBox, QTextEdit, QTabWidget, QWidget, QListWidget,
    QListWidgetItem, QGridLayout, QSpinBox, QScrollArea
)
from qgis.PyQt.QtCore import QVariant
import os.path
import re


class HelloWorld:
    """QGIS Plugin Implementation - Editor de Fórmulas Multi-Colunas"""

    def __init__(self, iface):
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        self.actions = []
        self.menu = self.tr(u'&Editor de Fórmulas')
        self.first_start = None

    def tr(self, message):
        return QCoreApplication.translate('HelloWorld', message)

    def add_action(self, icon_path, text, callback, parent=None):
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        self.iface.addPluginToMenu(self.menu, action)
        self.iface.addToolBarIcon(action)
        self.actions.append(action)
        return action

    def initGui(self):
        icon_path = os.path.join(os.path.dirname(__file__), 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr(u'📊 Editor de Fórmulas Multi-Colunas'),
            callback=self.run,
            parent=self.iface.mainWindow()
        )
        self.first_start = True

    def unload(self):
        for action in self.actions:
            self.iface.removePluginMenu(self.tr(u'&Editor de Fórmulas'), action)
            self.iface.removeToolBarIcon(action)

    # ============================================================
    # FUNÇÃO PRINCIPAL
    # ============================================================
    
    def run(self):
        layer = self.iface.activeLayer()
        
        if not layer or not isinstance(layer, QgsVectorLayer):
            QMessageBox.warning(self.iface.mainWindow(), "Aviso", 
                "Selecione uma camada vetorial na legenda.")
            return
        
        dialog = QDialog(self.iface.mainWindow())
        dialog.setWindowTitle("📊 Editor de Fórmulas com Múltiplas Colunas")
        dialog.setMinimumWidth(800)
        dialog.setMinimumHeight(600)
        dialog.setModal(True)
        
        layout_principal = QVBoxLayout()
        
        # === INFO DA CAMADA ===
        info_layer = QLabel(f"📌 Camada: {layer.name()} | Feições: {layer.featureCount()} | "
                           f"Selecionadas: {layer.selectedFeatureCount()}")
        info_layer.setStyleSheet("font-weight: bold; padding: 5px; background-color: #e3f2fd; border-radius: 3px;")
        layout_principal.addWidget(info_layer)
        
        # === ORGANIZAÇÃO EM GRADE ===
        grid = QGridLayout()
        
        # === 1. LISTA DE COLUNAS DE REFERÊNCIA ===
        lbl_colunas = QLabel("📋 Colunas de Referência (clique para adicionar):")
        grid.addWidget(lbl_colunas, 0, 0)
        
        # Lista de todas as colunas da camada
        list_colunas = QListWidget()
        list_colunas.setSelectionMode(QListWidget.MultiSelection)
        for field in layer.fields():
            item = QListWidgetItem(f"{field.name()} ({field.typeName()})")
            item.setData(Qt.UserRole, field.name())
            list_colunas.addItem(item)
        
        # Seleciona bal_perc e pop por padrão
        for i in range(list_colunas.count()):
            item = list_colunas.item(i)
            nome = item.data(Qt.UserRole)
            if nome in ['bal_perc', 'pop']:
                item.setSelected(True)
        
        grid.addWidget(list_colunas, 1, 0)
        
        # Botões para gerenciar colunas
        btn_adicionar = QPushButton("➕ Adicionar à Fórmula")
        btn_adicionar.setStyleSheet("background-color: #4CAF50; color: white; font-weight: bold;")
        btn_remover = QPushButton("➖ Remover da Fórmula")
        btn_remover.setStyleSheet("background-color: #f44336; color: white; font-weight: bold;")
        
        grid.addWidget(btn_adicionar, 2, 0)
        grid.addWidget(btn_remover, 3, 0)
        
        # === 2. CAMPOS SELECIONADOS PARA A FÓRMULA ===
        lbl_selecionados = QLabel("✅ Colunas Selecionadas para a Fórmula:")
        grid.addWidget(lbl_selecionados, 0, 1)
        
        list_selecionados = QListWidget()
        list_selecionados.setStyleSheet("background-color: #f0f8ff;")
        grid.addWidget(list_selecionados, 1, 1)
        
        # === 3. CONSTRUTOR DA FÓRMULA ===
        lbl_formula = QLabel("📝 Fórmula (use os nomes das colunas entre chaves { }):")
        grid.addWidget(lbl_formula, 0, 2)
        
        input_formula = QTextEdit()
        input_formula.setPlaceholderText("Ex: {pop} / {area} * 1000\n\n"
                                         "Use: {nome_coluna} para referenciar valores\n"
                                         "Operadores: + - * / ** ( )\n"
                                         "Funções: abs(), round(), sqrt(), log()")
        input_formula.setMaximumHeight(100)
        grid.addWidget(input_formula, 1, 2)
        
        # Botão para inserir coluna na fórmula
        btn_inserir_coluna = QPushButton("📥 Inserir Coluna na Fórmula")
        btn_inserir_coluna.setStyleSheet("background-color: #FF9800; color: white; font-weight: bold;")
        grid.addWidget(btn_inserir_coluna, 2, 2)
        
        # === 4. CAMPO DE DESTINO ===
        lbl_destino = QLabel("🎯 Campo de Destino:")
        grid.addWidget(lbl_destino, 3, 0)
        
        combo_destino = QComboBox()
        # Adiciona opção para criar novo campo
        combo_destino.addItem("➕ Criar novo campo...", "__new__")
        for field in layer.fields():
            combo_destino.addItem(f"{field.name()} ({field.typeName()})", field.name())
        grid.addWidget(combo_destino, 3, 1)
        
        # Nome do novo campo (aparece quando seleciona "Criar novo campo")
        lbl_novo_campo = QLabel("Nome do novo campo:")
        lbl_novo_campo.setVisible(False)
        grid.addWidget(lbl_novo_campo, 4, 0)
        
        input_novo_campo = QLineEdit()
        input_novo_campo.setPlaceholderText("Ex: densidade, indice, total")
        input_novo_campo.setVisible(False)
        grid.addWidget(input_novo_campo, 4, 1)
        
        # Tipo do novo campo
        lbl_tipo_campo = QLabel("Tipo do novo campo:")
        lbl_tipo_campo.setVisible(False)
        grid.addWidget(lbl_tipo_campo, 5, 0)
        
        combo_tipo = QComboBox()
        combo_tipo.addItems(["Double (decimal)", "Integer (inteiro)", "String (texto)"])
        combo_tipo.setVisible(False)
        grid.addWidget(combo_tipo, 5, 1)
        
        # === 5. FILTRO ===
        lbl_filtro = QLabel("🔍 Filtro (opcional):")
        grid.addWidget(lbl_filtro, 6, 0)
        
        input_filtro = QLineEdit()
        input_filtro.setPlaceholderText('Ex: "pop" > 100 AND "categoria" = \'A\'')
        grid.addWidget(input_filtro, 6, 1, 1, 2)
        
        # === 6. PRÉ-VISUALIZAÇÃO ===
        lbl_preview = QLabel("👁️ Pré-visualização:")
        grid.addWidget(lbl_preview, 7, 0)
        
        text_preview = QTextEdit()
        text_preview.setReadOnly(True)
        text_preview.setMaximumHeight(150)
        text_preview.setStyleSheet("font-family: monospace; font-size: 10pt;")
        grid.addWidget(text_preview, 8, 0, 1, 3)
        
        # Botão atualizar preview
        btn_preview = QPushButton("🔍 Atualizar Pré-visualização")
        btn_preview.setStyleSheet("background-color: #FF9800; color: white; font-weight: bold; padding: 5px;")
        grid.addWidget(btn_preview, 9, 0, 1, 3)
        
        layout_principal.addLayout(grid)
        
        # === BOTÕES DE AÇÃO ===
        layout_botoes = QHBoxLayout()
        
        btn_aplicar = QPushButton("✅ Aplicar Fórmula")
        btn_aplicar.setStyleSheet("""
            QPushButton {
                background-color: #4CAF50; 
                color: white; 
                font-weight: bold; 
                padding: 12px;
                border-radius: 5px;
                font-size: 12pt;
            }
            QPushButton:hover { background-color: #45a049; }
        """)
        
        btn_fechar = QPushButton("❌ Fechar")
        btn_fechar.setStyleSheet("""
            QPushButton {
                background-color: #f44336; 
                color: white; 
                font-weight: bold; 
                padding: 12px;
                border-radius: 5px;
            }
            QPushButton:hover { background-color: #D32F2F; }
        """)
        
        layout_botoes.addWidget(btn_aplicar)
        layout_botoes.addWidget(btn_fechar)
        layout_principal.addLayout(layout_botoes)
        
        dialog.setLayout(layout_principal)
        
        # ============================================================
        # FUNÇÕES DO DIÁLOGO
        # ============================================================
        
        def atualizar_selecionados():
            """Atualiza lista de colunas selecionadas"""
            list_selecionados.clear()
            for item in list_colunas.selectedItems():
                nome = item.data(Qt.UserRole)
                list_selecionados.addItem(nome)
        
        def adicionar_colunas():
            """Adiciona colunas selecionadas à fórmula"""
            # Pega a fórmula atual
            formula_atual = input_formula.toPlainText()
            
            # Adiciona as colunas selecionadas
            for item in list_colunas.selectedItems():
                nome = item.data(Qt.UserRole)
                if nome not in formula_atual:
                    if formula_atual and not formula_atual.endswith('\n'):
                        formula_atual += '\n'
                    formula_atual += f'{{{nome}}}'
            
            input_formula.setText(formula_atual)
            atualizar_selecionados()
        
        def remover_colunas():
            """Remove colunas selecionadas da lista e da fórmula"""
            # Remove da lista
            for item in list_selecionados.selectedItems():
                row = list_selecionados.row(item)
                list_selecionados.takeItem(row)
            
            # Atualiza a fórmula (remove as colunas que não estão mais na lista)
            colunas_selecionadas = [list_selecionados.item(i).text() for i in range(list_selecionados.count())]
            
            # Pega a fórmula atual
            formula = input_formula.toPlainText()
            
            # Remove referências a colunas que não estão mais selecionadas
            # Encontra todas as colunas na fórmula
            padrao = r'\{([^}]+)\}'
            colunas_na_formula = re.findall(padrao, formula)
            
            for coluna in colunas_na_formula:
                if coluna not in colunas_selecionadas:
                    formula = formula.replace(f'{{{coluna}}}', '')
            
            # Limpa espaços extras
            formula = re.sub(r'\n\s*\n', '\n', formula).strip()
            input_formula.setText(formula)
        
        def inserir_coluna_na_formula():
            """Insere a coluna selecionada na posição do cursor"""
            if not list_selecionados.selectedItems():
                QMessageBox.warning(dialog, "Aviso", "Selecione uma coluna na lista de selecionadas.")
                return
            
            coluna = list_selecionados.selectedItems()[0].text()
            cursor = input_formula.textCursor()
            cursor.insertText(f'{{{coluna}}}')
            input_formula.setTextCursor(cursor)
        
        def extrair_colunas_da_formula():
            """Extrai colunas da fórmula e adiciona à lista de selecionadas"""
            formula = input_formula.toPlainText()
            padrao = r'\{([^}]+)\}'
            colunas_encontradas = re.findall(padrao, formula)
            
            # Limpa seleção atual
            list_selecionados.clear()
            
            # Adiciona colunas encontradas
            for coluna in colunas_encontradas:
                list_selecionados.addItem(coluna)
            
            # Seleciona essas colunas na lista principal
            for i in range(list_colunas.count()):
                item = list_colunas.item(i)
                nome = item.data(Qt.UserRole)
                if nome in colunas_encontradas:
                    item.setSelected(True)
        
        def get_features_to_edit():
            """Retorna as feições que serão editadas"""
            filtro = input_filtro.text().strip()
            
            if filtro:
                try:
                    expr = QgsExpression(filtro)
                    request = QgsFeatureRequest(expr)
                    return list(layer.getFeatures(request))
                except:
                    return list(layer.getFeatures())
            else:
                return list(layer.getFeatures())
        
        def calcular_valor(feature, formula, colunas):
            """Calcula o valor da fórmula para uma feição"""
            try:
                # Substitui {coluna} pelos valores reais
                formula_calculada = formula
                
                # Extrai todas as colunas da fórmula
                padrao = r'\{([^}]+)\}'
                colunas_encontradas = re.findall(padrao, formula)
                
                # Substitui cada coluna pelo seu valor
                for coluna in colunas_encontradas:
                    valor = feature.attribute(coluna)
                    
                    # Se for string, coloca entre aspas
                    if isinstance(valor, str):
                        valor = f'"{valor}"'
                    elif valor is None:
                        valor = 'None'
                    
                    formula_calculada = formula_calculada.replace(f'{{{coluna}}}', str(valor))
                
                # Calcula a fórmula
                resultado = eval(formula_calculada)
                return resultado
                
            except Exception as e:
                return None
        
        def preview_alteracoes():
            """Mostra pré-visualização das alterações"""
            formula = input_formula.toPlainText().strip()
            
            if not formula:
                text_preview.setText("⚠️ Digite uma fórmula primeiro.\n\n"
                                     "Use {nome_coluna} para referenciar valores.")
                return
            
            # Extrai colunas da fórmula
            padrao = r'\{([^}]+)\}'
            colunas = re.findall(padrao, formula)
            
            if not colunas:
                text_preview.setText("⚠️ Nenhuma coluna encontrada na fórmula.\n\n"
                                     "Use {nome_coluna} para referenciar valores.")
                return
            
            features = get_features_to_edit()
            
            if not features:
                text_preview.setText("⚠️ Nenhuma feição encontrada com os critérios atuais.")
                return
            
            # Constroi preview
            texto = f"📋 Fórmula: {formula}\n"
            texto += f"📌 Colunas usadas: {', '.join(colunas)}\n"
            texto += f"📌 Feições afetadas: {len(features)}\n"
            texto += "━" * 50 + "\n\n"
            
            count = 0
            erros = 0
            
            for feat in features[:10]:
                try:
                    # Mostra os valores das colunas
                    valores = []
                    for col in colunas:
                        val = feat.attribute(col)
                        valores.append(f"{col}={val}")
                    
                    resultado = calcular_valor(feat, formula, colunas)
                    
                    if resultado is not None:
                        texto += f"Feição {feat.id()}: {', '.join(valores)} → RESULTADO: {resultado}\n"
                        count += 1
                    else:
                        texto += f"Feição {feat.id()}: ⚠️ Erro ao calcular\n"
                        erros += 1
                except:
                    texto += f"Feição {feat.id()}: ⚠️ Erro ao processar\n"
                    erros += 1
            
            if len(features) > 10:
                texto += f"\n... e mais {len(features) - 10} feições"
            
            if count == 0:
                texto += "\n\n⚠️ Nenhuma feição pôde ser calculada. Verifique a fórmula."
            else:
                texto += f"\n\n✅ {count} feições calculadas com sucesso | ❌ {erros} erros"
            
            text_preview.setText(texto)
        
        def aplicar_formula():
            """Aplica a fórmula nas feições"""
            formula = input_formula.toPlainText().strip()
            
            if not formula:
                QMessageBox.warning(dialog, "Aviso", "Digite uma fórmula.")
                return
            
            # Extrai colunas da fórmula
            padrao = r'\{([^}]+)\}'
            colunas = re.findall(padrao, formula)
            
            if not colunas:
                QMessageBox.warning(dialog, "Aviso", 
                    "Nenhuma coluna encontrada na fórmula.\nUse {nome_coluna}.")
                return
            
            # Verifica se as colunas existem
            for col in colunas:
                if col not in [f.name() for f in layer.fields()]:
                    QMessageBox.warning(dialog, "Aviso", 
                        f"Coluna '{col}' não encontrada na camada.")
                    return
            
            features = get_features_to_edit()
            
            if not features:
                QMessageBox.warning(dialog, "Aviso", "Nenhuma feição encontrada para editar.")
                return
            
            # Define o campo de destino
            destino = combo_destino.currentData()
            novo_nome = None
            
            if destino == "__new__":
                novo_nome = input_novo_campo.text().strip()
                if not novo_nome:
                    QMessageBox.warning(dialog, "Aviso", "Digite um nome para o novo campo.")
                    return
                
                # Verifica se o campo já existe
                if novo_nome in [f.name() for f in layer.fields()]:
                    QMessageBox.warning(dialog, "Aviso", 
                        f"O campo '{novo_nome}' já existe. Escolha outro nome.")
                    return
                
                # Tipo do novo campo
                tipo_idx = combo_tipo.currentIndex()
                if tipo_idx == 0:  # Double
                    novo_campo = QgsField(novo_nome, QVariant.Double)
                elif tipo_idx == 1:  # Integer
                    novo_campo = QgsField(novo_nome, QVariant.Int)
                else:  # String
                    novo_campo = QgsField(novo_nome, QVariant.String)
                
                # Adiciona o campo à camada
                if not layer.dataProvider().addAttributes([novo_campo]):
                    QMessageBox.critical(dialog, "Erro", "Não foi possível criar o novo campo.")
                    return
                layer.updateFields()
                
                destino = novo_nome
            else:
                # Verifica se o campo destino existe
                if destino not in [f.name() for f in layer.fields()]:
                    QMessageBox.warning(dialog, "Aviso", 
                        f"Campo destino '{destino}' não encontrado.")
                    return
            
            # Conta quantas serão calculadas
            validas = 0
            for feat in features:
                resultado = calcular_valor(feat, formula, colunas)
                if resultado is not None:
                    validas += 1
            
            if validas == 0:
                QMessageBox.warning(dialog, "Aviso", 
                    "Nenhuma feição pôde ser calculada. Verifique a fórmula.")
                return
            
            # Confirmação
            resposta = QMessageBox.question(
                dialog,
                "Confirmar",
                f"Tem certeza que deseja aplicar a fórmula?\n\n"
                f"📌 Feições afetadas: {validas}\n"
                f"📝 Fórmula: {formula}\n"
                f"🎯 Campo destino: {destino}\n\n"
                f"⚠️ Esta ação não pode ser desfeita!",
                QMessageBox.Yes | QMessageBox.No
            )
            
            if resposta != QMessageBox.Yes:
                return
            
            # Aplica
            try:
                if not layer.isEditable():
                    layer.startEditing()
                
                count = 0
                erros = 0
                
                for feat in features:
                    resultado = calcular_valor(feat, formula, colunas)
                    
                    if resultado is not None:
                        # Converte para o tipo correto
                        field = layer.fields().field(destino)
                        tipo = field.type()
                        
                        if tipo in (QVariant.Int, QVariant.LongLong):
                            resultado = int(resultado)
                        elif tipo in (QVariant.Double, QVariant.UserType):
                            resultado = float(resultado)
                        
                        feat.setAttribute(destino, resultado)
                        layer.updateFeature(feat)
                        count += 1
                    else:
                        erros += 1
                
                # Salva
                if layer.commitChanges():
                    QMessageBox.information(dialog, "✅ Sucesso", 
                        f"{count} feição(ões) atualizadas com sucesso!\n\n"
                        f"📝 Fórmula: {formula}\n"
                        f"🎯 Campo destino: {destino}\n"
                        f"❌ Erros: {erros}"
                    )
                    dialog.accept()
                    self.iface.mapCanvas().refresh()
                else:
                    erros_commit = layer.commitErrors()
                    QMessageBox.critical(dialog, "❌ Erro", 
                        f"Erro ao salvar:\n{erros_commit}")
                    layer.rollBack()
                    
            except Exception as e:
                QMessageBox.critical(dialog, "❌ Erro", f"Erro ao aplicar: {str(e)}")
                if layer.isEditable():
                    layer.rollBack()
        
        # ============================================================
        # CONEXÕES DOS BOTÕES
        # ============================================================
        
        list_colunas.itemSelectionChanged.connect(atualizar_selecionados)
        btn_adicionar.clicked.connect(adicionar_colunas)
        btn_remover.clicked.connect(remover_colunas)
        btn_inserir_coluna.clicked.connect(inserir_coluna_na_formula)
        btn_preview.clicked.connect(preview_alteracoes)
        btn_aplicar.clicked.connect(aplicar_formula)
        btn_fechar.clicked.connect(dialog.reject)
        
        # Preview automático quando a fórmula muda
        input_formula.textChanged.connect(preview_alteracoes)
        
        # Mostra/esconde campos de novo campo
        def on_destino_changed(index):
            is_new = combo_destino.currentData() == "__new__"
            lbl_novo_campo.setVisible(is_new)
            input_novo_campo.setVisible(is_new)
            lbl_tipo_campo.setVisible(is_new)
            combo_tipo.setVisible(is_new)
        
        combo_destino.currentIndexChanged.connect(on_destino_changed)
        
        # Preview inicial
        preview_alteracoes()
        
        dialog.exec_()