id: humano
description: "Calculando a dimensão humana"
base_dir: "."

bho:
  path: "/home/luca_profissional/Desktop/BolsaLabgest/ish_lunc/cnr_A/input/BHO_area.gpkg"

dimensions:
  - name: ire_cs_hum
    path: "/home/luca_profissional/Desktop/BolsaLabgest/ish_lunc/functions_module_ish_hum/dimensao_humana.csv"
    indicadores:
      - name: disp_por_dem
        depends_on: bal_perc
        pesos: [3]
      - name: fator_iminente
      - name: fator_pos_deficit
      - name: fator_de_risco_total
      - name: ihu_nu_popriscoinerente
      - name: ihu_pc_risco_inerente
      - name: ihu_nu_popriscoposdeficit
      - name: ihu_pc_riscoposdeficit
      - name: ihu_nu_popriscototal
      - name: ihu_pc_risco
      - name: densidade
      - name: cs_risco
      - name: cs_cobred
      - name: perc_scbc
      - name: ihu_cs_ish
      - name: ihu_rel_pop
      - name: ihu_rel_cobred
      - name: ire_hu_pop
      - name: ire_hu_cobred
    descritor: tipo_setor

result:
  - name: ire_cs_hum
    depends_on:
      - name: ire_hu_cobred
        peso: 0.3
      - name: ire_hu_pop
        peso: 0.7

# Saída: pode opcionalmente sobrescrever pasta output/gpkg final
output:
  path: "/home/luca_profissional/Desktop/BolsaLabgest/ish_lunc/functions_module_ish_hum/output/ish_hum.csv"
 
